language: node_js
branches:
    only:
        - "/^\\d+\\.\\d+\\.\\d+$/"
        - "/^\\d+\\.\\d+\\.\\d+(-alpha)$/"
        - "/^\\d+\\.\\d+\\.\\d+(-beta\\.\\d+)$/"
        - "/^\\d+\\.\\d+\\.\\d+(-dev\\.\\d+)$/"
git:
    depth: 1
node_js:
    - '12'
cache:
    directories:
        - '$HOME/node_modules'
        - '$HOME/.meteor'
        - '$HOME/.npm'
        - '$HOME/.node-gyp'
install:
    - if [ ! -e "$HOME/.meteor/meteor" ]; then curl https://install.meteor.com | sed s/--progress-bar/-sL/g
      | /bin/sh; fi
    - export PATH="$HOME/.meteor:$PATH"
script:
    - meteor --version
    - meteor npm install
    - meteor build --server-only /tmp/build
deploy:
    provider: releases
    api_key:
        secure: ej2yXJumvq3wdB++2rlV0DThQyuemg4gLAxn+WX3yJ8DZ377Lqmz+wLPnbPcxoaBvqq3+aIo65b2HVzILXU/euVfvHnGgh1WomTGrzp0Uri7ANEX9cMn7stwx7dXG6nT6da7LNaTRPOBZTt/Vkk0WFthqTxv9rfx+TAGNPtvEKoGL3HscSEsos+EXFaVv5uZ+uqiIbuyAl6VXsRiOPagsGVLuaDnlSEmH9PMbKUhbWhL7z7lJAyITSmA6fdY5CAsedELRudycP27S0cPhF1pwAA1f94WkUDQyYUcfTq6JZlrO8TlXKeeY2uIcnLX2OgeRHEuyKJ8mJZ3fPqediSbwjIuDdMEF3Lt1WxdQkgeNTuoQsGoINXbmXOZqNLWN8cPKlxPprj54KQUA9g05yJxaloC/bl5RCU2irM2a5uPcRGL0CDJmeRmWrlJho3K13fZP6Dy7Hj7c3b8Z3kbEYzUdI76c+7I9Z+nwEpKclQGfHEKRtC5kkwD2mI967htiA+ir9/AIO1Xb4BH4ugO0tk+KRVfF/j8KcA7H/Fn3Ynewhkhb3HgYA2b7fCnhTxx6aW/TZ28toaSqHKIDG1W849Oaxce563/u6GMgMBDfGCMi/URjOwzNxAs1lbe2T07dfEJOienG0TfHyT2QX72SvI39Bxio6KH0m7brm0sSJqGKvE=
    skip_cleanup: true
    file: '/tmp/build/Konecty.tar.gz'
    on:
        tags: true
after_deploy:
    - |
        curl -H "Content-Type: application/json" \
        --data '{"source_type":"Tag","source_name":"'"$TRAVIS_TAG"'"}' \
        -X POST "https://hub.docker.com/api/build/v1/source/$DOCKERHUB_TOKEN/trigger/$DOCKERHUB_BUILD/call/"
